<?php
/**
 * MegaGovern — Shared Data Helper — V1.0.4
 * 
 * Central place for all repeated arrays: icons, labels, colors, action types.
 * Every other class loads this once and calls static methods.
 *
 * @package MegaGovern
 * @since   1.0.4
 */
namespace MegaGovern;
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}
class Helpers {
    /**
     * Declaration type map — Unified labels + EU AI Act Article 50 data.
     *
     * @return array
     */
    public static function declaration_types(): array {
        return [
            'human'        => [
                'key'            => 'human',
                'label'          => __( 'Human Authored', 'megagovern' ),
                'icon'           => 'lucide-user',
                'color'          => '#2271b1',
                'bg'             => '#f0f6fc',
                'css'            => 'mga-status-human',
                'eu_aria'        => 'AI Transparency Label — General AI involvement indicator per EU AI Act Article 50',
                'eu_description' => 'This content carries an AI transparency label for general disclosure. The label indicates AI tools may have been involved in the content creation process.',
            ],
            'ai_assisted'  => [
                'key'            => 'ai_assisted',
                'label'          => __( 'AI Assisted', 'megagovern' ),
                'icon'           => 'lucide-pencil',
                'color'          => '#dba617',
                'bg'             => '#fffbeb',
                'css'            => 'mga-status-assisted',
                'eu_aria'        => 'Partially AI-Modified Content — Human-created content modified with artificial intelligence tools',
                'eu_description' => 'This content was originally created by a human author but has been modified, enhanced, or partially generated using artificial intelligence tools.',
            ],
            'ai_generated' => [
                'key'            => 'ai_generated',
                'label'          => __( 'AI Generated', 'megagovern' ),
                'icon'           => 'lucide-brain',
                'color'          => '#d63638',
                'bg'             => '#fef2f2',
                'css'            => 'mga-status-generated',
                'eu_aria'        => 'Fully AI-Generated Content — Content entirely generated by artificial intelligence with no human editorial intervention',
                'eu_description' => 'This content was entirely generated by artificial intelligence. No human editorial intervention was applied beyond the initial prompt or instruction.',
            ],
            'deepfake'     => [
                'key'            => 'deepfake',
                'label'          => __( 'Synthetic Media', 'megagovern' ),
                'icon'           => 'lucide-scan',
                'color'          => '#d63638',
                'bg'             => '#fef2f2',
                'css'            => 'mga-status-deepfake',
                'eu_aria'        => 'Deepfake or Synthetic Media — AI-generated or manipulated content per EU AI Act Article 50',
                'eu_description' => 'This media has been identified as AI-generated or synthetically manipulated content.',
            ],
        ];
    }
    /**
     * Get a single declaration type by key.
     *
     * @param string $key human|ai_assisted|ai_generated|deepfake
     * @return array|null
     */
    public static function declaration_type( string $key ): ?array {
        $types = self::declaration_types();
        return $types[ $key ] ?? null;
    }
    /**
     * Get declaration type label.
     *
     * @param string $key
     * @return string
     */
    public static function declaration_label( string $key ): string {
        $type = self::declaration_type( $key );
        return $type['label'] ?? __( 'Unknown', 'megagovern' );
    }
    /**
     * Get declaration type icon.
     *
     * @param string $key
     * @return string
     */
    public static function declaration_icon( string $key ): string {
        $type = self::declaration_type( $key );
        return $type['icon'] ?? 'lucide-help-circle';
    }
    /**
     * Media declaration types for attachment fields.
     *
     * @return array
     */
    public static function media_declaration_types(): array {
        return [
            ''              => __( 'None', 'megagovern' ),
            'human'         => __( 'Human Created', 'megagovern' ),
            'ai_assisted'   => __( 'AI Assisted', 'megagovern' ),
            'ai_generated'  => __( 'AI Generated', 'megagovern' ),
            'deepfake'      => __( 'Synthetic Media', 'megagovern' ),
        ];
    }
    /**
     * Governance action icons.
     *
     * @return array
     */
    public static function action_icons(): array {
        return [
            'classified'           => 'lucide-tag',
            'reclassified'         => 'lucide-refresh-cw',
            'documented'           => 'lucide-database',
            'aitxt_published'      => 'lucide-file-text',
            'label_displayed'      => 'lucide-badge',
            'report_generated'     => 'lucide-file',
            'verification_updated' => 'lucide-shield',
            'alert_received'       => 'lucide-bell',
            'issue_fixed'          => 'lucide-check',
            'services_updated'     => 'lucide-wrench',
            'crawler_blocked'      => 'lucide-shield-off',
        ];
    }
    /**
     * Get action icon by action key.
     *
     * @param string $action
     * @return string
     */
    public static function action_icon( string $action ): string {
        $icons = self::action_icons();
        return $icons[ $action ] ?? 'lucide-tool';
    }
    /**
     * Governance action labels.
     *
     * @return array
     */
    public static function action_labels(): array {
        return [
            'classified'           => __( 'Article declared', 'megagovern' ),
            'reclassified'         => __( 'Declaration updated', 'megagovern' ),
            'documented'           => __( 'Registry updated', 'megagovern' ),
            'aitxt_published'      => __( 'AI.txt regenerated', 'megagovern' ),
            'label_displayed'      => __( 'Label displayed', 'megagovern' ),
            'report_generated'     => __( 'Report generated', 'megagovern' ),
            'verification_updated' => __( 'Verification updated', 'megagovern' ),
            'alert_received'       => __( 'Alert received', 'megagovern' ),
            'issue_fixed'          => __( 'Issue fixed', 'megagovern' ),
            'services_updated'     => __( 'Services refreshed', 'megagovern' ),
            'crawler_blocked'      => __( 'Crawler blocked', 'megagovern' ),
        ];
    }
    /**
     * Get action label by action key.
     *
     * @param string $action
     * @return string
     */
    public static function action_label( string $action ): string {
        $labels = self::action_labels();
        return $labels[ $action ] ?? ucfirst( str_replace( '_', ' ', $action ) );
    }
    /**
     * Issue severity config.
     *
     * @return array
     */
    public static function severity_levels(): array {
        return [
            'high'   => [
                'color' => '#d63638',
                'bg'    => '#fcf0f1',
                'icon'  => 'lucide-alert-circle',
                'label' => __( 'High', 'megagovern' ),
            ],
            'medium' => [
                'color' => '#dba617',
                'bg'    => '#fcf9e8',
                'icon'  => 'lucide-alert-triangle',
                'label' => __( 'Medium', 'megagovern' ),
            ],
            'low'    => [
                'color' => '#00a32a',
                'bg'    => '#f0f6fc',
                'icon'  => 'lucide-info',
                'label' => __( 'Low', 'megagovern' ),
            ],
        ];
    }
    /**
     * Health state config.
     *
     * @return array
     */
    public static function health_states(): array {
        return [
            'good'     => [
                'color' => '#00a32a',
                'bg'    => '#f0f6fc',
                'icon'  => 'lucide-circle-check',
                'label' => __( 'Healthy', 'megagovern' ),
            ],
            'warning'  => [
                'color' => '#dba617',
                'bg'    => '#fcf9e8',
                'icon'  => 'lucide-triangle-alert',
                'label' => __( 'Warning', 'megagovern' ),
            ],
            'critical' => [
                'color' => '#d63638',
                'bg'    => '#fcf0f1',
                'icon'  => 'lucide-circle-alert',
                'label' => __( 'Critical', 'megagovern' ),
            ],
        ];
    }
    /**
     * Jurisdiction labels for alerts.
     *
     * @return array
     */
    public static function jurisdictions(): array {
        return [
            'eu'     => [
                'icon'  => 'lucide-flag',
                'label' => __( 'European Union', 'megagovern' ),
            ],
            'us'     => [
                'icon'  => 'lucide-flag',
                'label' => __( 'United States', 'megagovern' ),
            ],
            'global' => [
                'icon'  => 'lucide-globe',
                'label' => __( 'Global', 'megagovern' ),
            ],
        ];
    }
    /**
     * Get jurisdiction label.
     *
     * @param string $key
     * @return string
     */
    public static function jurisdiction_label( string $key ): string {
        $jurisdictions = self::jurisdictions();
        return $jurisdictions[ $key ]['label'] ?? __( 'General', 'megagovern' );
    }
    /**
     * Get jurisdiction icon.
     *
     * @param string $key
     * @return string
     */
    public static function jurisdiction_icon( string $key ): string {
        $jurisdictions = self::jurisdictions();
        return $jurisdictions[ $key ]['icon'] ?? 'lucide-globe';
    }
    /**
     * Score label based on percentage.
     *
     * @param int $score 0-100
     * @return string
     */
    public static function score_label( int $score ): string {
        if ( $score >= 71 ) {
            return __( 'Excellent', 'megagovern' );
        }
        if ( $score >= 51 ) {
            return __( 'Good', 'megagovern' );
        }
        if ( $score >= 31 ) {
            return __( 'Fair', 'megagovern' );
        }
        return __( 'Needs Attention', 'megagovern' );
    }
    /**
     * Score color based on percentage.
     *
     * @param int $score 0-100
     * @return string hex color
     */
    public static function score_color( int $score ): string {
        if ( $score >= 71 ) {
            return '#00a32a';
        }
        if ( $score >= 51 ) {
            return '#dba617';
        }
        return '#d63638';
    }
    /**
     * Plan badge CSS class.
     *
     * @param string $plan Free|Pro|Lifetime|Agency
     * @return string
     */
    public static function plan_badge_class( string $plan ): string {
        $map = [
            'Free'     => 'mga-pill--warn',
            'Pro'      => 'mga-pill--ok',
            'Lifetime' => 'mga-pill--ok',
            'Agency'   => 'mga-pill--ok',
        ];
        return $map[ $plan ] ?? 'mga-pill--warn';
    }
    /**
     * Get all crawler bot user-agent patterns.
     *
     * @return array
     */
    public static function crawler_bots(): array {
        return [
            'GPTBot'                 => 'OpenAI GPTBot',
            'ChatGPT-User'           => 'OpenAI ChatGPT User',
            'CCBot'                  => 'Common Crawl',
            'anthropic-ai'           => 'Anthropic Claude',
            'Claude-Web'             => 'Anthropic Claude Web',
            'cohere-ai'              => 'Cohere AI',
            'Google-Extended'        => 'Google Extended',
            'GoogleOther'            => 'Google Other',
            'GoogleOther-Image'      => 'Google Other Image',
            'GoogleOther-Video'      => 'Google Other Video',
            'Bytespider'             => 'ByteDance (TikTok)',
            'Newsbreak'              => 'NewsBreak',
            'Omgili'                 => 'Omgili Bot',
            'Omgilibot'              => 'Omgili Bot',
            'PerplexityBot'          => 'Perplexity AI',
            'YouBot'                 => 'You.com',
            'Diffbot'                => 'Diffbot',
            'ImagesiftBot'           => 'ImageSift',
            'facebookexternalua'     => 'Meta Facebook',
            'Meta-ExternalAgent'     => 'Meta AI',
            'Amazonbot'              => 'Amazon Alexa',
            'Applebot'               => 'Apple Bot',
            'Applebot-Extended'      => 'Apple Extended',
            'PetalBot'               => 'Huawei Petal',
            'Barkrowler'             => 'Babbar',
            'PiplBot'                => 'Pipl',
            'DataForSeoBot'          => 'DataForSEO',
            'SeekportBot'            => 'Seekport',
            'Sidetrade'              => 'Sidetrade',
            'trendictionbot'         => 'Trendiction',
            'VelenPublicWebCrawler'  => 'Velen',
            'Webzio-Extended'        => 'Webzio',
        ];
    }
    /**
     * Get formatted type label (handles both string and int).
     *
     * @param string|int $type
     * @return string
     */
    public static function format_type( $type ): string {
        $map = [
            0              => __( 'Human Authored', 'megagovern' ),
            1              => __( 'AI Assisted', 'megagovern' ),
            2              => __( 'AI Generated', 'megagovern' ),
            3              => __( 'Synthetic Media', 'megagovern' ),
            'human'        => __( 'Human Authored', 'megagovern' ),
            'ai_assisted'  => __( 'AI Assisted', 'megagovern' ),
            'ai_generated' => __( 'AI Generated', 'megagovern' ),
            'deepfake'     => __( 'Synthetic Media', 'megagovern' ),
        ];
        return $map[ $type ] ?? __( 'Unknown', 'megagovern' );
    }
    /**
     * Get severity icon.
     *
     * @param string $level high|medium|low
     * @return string
     */
    public static function severity_icon( string $level ): string {
        $levels = self::severity_levels();
        return $levels[ $level ]['icon'] ?? 'lucide-info';
    }
    /**
     * Get health state icon.
     *
     * @param string $state good|warning|critical
     * @return string
     */
    public static function health_icon( string $state ): string {
        $states = self::health_states();
        return $states[ $state ]['icon'] ?? 'lucide-info';
    }
}